"""TrackerType name changed

Revision ID: 76965cdb48ee
Revises: 138ad531b560
Create Date: 2022-09-27 01:10:12.898563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76965cdb48ee'
down_revision = '138ad531b560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker', sa.Column('tracker_type', sa.String(length=100), nullable=False))
    op.drop_column('tracker', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker', sa.Column('password_hash', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('tracker', 'tracker_type')
    # ### end Alembic commands ###
