"""Card Created.

Revision ID: 9d8aa09b1722
Revises: 76965cdb48ee
Create Date: 2022-09-27 23:11:10.380589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8aa09b1722'
down_revision = '76965cdb48ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tracker_id'], ['tracker.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
